name = "my-wakatime-worker"
main = "src/index.ts"
compatibility_date = "2024-06-18"
node_compat = true

[build]
command = "npm run build"
cache = { type = "local" }

[dev]
port = 8787
ip = "localhost"

[triggers]
routes = [
  "https://wakatime-stats.your-domain.com/*"
]